import jsPDF from 'jspdf';

export const generateCISOReport = (aiResponse: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, size: number, style: 'normal' | 'bold' = 'normal', color: [number, number, number] = [30, 30, 30]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += size * 0.5;
    }
    y += 4;
  };

  const addSeparator = () => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setDrawColor(0, 150, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 45, 'F');
  doc.setTextColor(100, 210, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('HiCompliance AI CISO Report', margin, 28);
  doc.setFontSize(10);
  doc.setTextColor(150, 180, 200);
  doc.text(`Report generato il: ${new Date().toLocaleString('it-IT')}`, margin, 38);
  y = 55;

  // Parse markdown sections
  const sections = aiResponse.split(/^#{1,3}\s+/m).filter(Boolean);
  
  if (sections.length > 1) {
    // Multiple sections found, process each
    const fullSections = aiResponse.split(/(?=^#{1,3}\s+)/m).filter(Boolean);
    for (const section of fullSections) {
      const lines = section.trim().split('\n');
      const titleMatch = lines[0].match(/^#{1,3}\s+(.+)/);
      if (titleMatch) {
        addSeparator();
        addText(titleMatch[1], 14, 'bold', [60, 180, 230]);
        const body = lines.slice(1).join('\n').trim();
        if (body) {
          // Clean markdown formatting
          const cleaned = body
            .replace(/\*\*(.*?)\*\*/g, '$1')
            .replace(/\*(.*?)\*/g, '$1')
            .replace(/`(.*?)`/g, '$1')
            .replace(/^[-•]\s*/gm, '• ');
          addText(cleaned, 10);
        }
      } else {
        addText(section.trim(), 10);
      }
    }
  } else {
    // No markdown headers, treat as plain text
    addText(aiResponse, 10);
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 282, pageWidth, 15, 'F');
    doc.setFontSize(8);
    doc.setTextColor(100, 150, 180);
    doc.text('Generated by AI CISO Assistant — HiCompliance', margin, 290);
    doc.text(`Pagina ${i}/${totalPages}`, pageWidth - margin - 25, 290);
  }

  doc.save(`AI_CISO_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};
