-- Seed assessment categories
INSERT INTO assessment_categories (name, code, order_index, description) VALUES
  ('Business Continuity, Disaster recovery, Backup', 'bcp', 0, 'Piani e procedure per garantire la continuità operativa e il ripristino in caso di disastro.'),
  ('Certificazioni', 'cert', 1, 'Adozione e mantenimento di certificazioni di sicurezza (ISO 27001).'),
  ('Crittografia', 'crypto', 2, 'Utilizzo e gestione della crittografia per la protezione dei dati.'),
  ('Gestione delle identità Gestione degli accessi', 'iam', 3, 'Controllo degli accessi, autenticazione e gestione delle identità digitali.'),
  ('Gestione degli incidenti', 'incident', 4, 'Preparazione, rilevamento e gestione degli incidenti di sicurezza informatica.'),
  ('Gestione del rischio', 'risk', 5, 'Processi strutturati di valutazione e gestione dei rischi cyber secondo le normative NIS2.'),
  ('Gestione delle risorse', 'asset', 6, 'Identificazione, classificazione e gestione delle risorse e degli asset IT.'),
  ('Gestione fornitori e acquisti', 'supply', 7, 'Valutazione e gestione dei rischi legati ai fornitori e alla catena di approvvigionamento.'),
  ('Governance', 'gov', 8, 'Struttura di gestione della sicurezza, definizione delle responsabilità, strategie e politiche di cybersecurity.'),
  ('HR e formazione', 'hr', 9, 'Formazione del personale, consapevolezza e gestione delle competenze in ambito cybersecurity.'),
  ('Igiene informatica', 'hygiene', 10, 'Pratiche fondamentali di igiene informatica per la protezione quotidiana.'),
  ('Manutenzione e miglioramento continuo', 'maint', 11, 'Processi di reporting, comunicazione delle violazioni e conformità agli obblighi normativi.'),
  ('Network Security Best Practices & Operations', 'netsec', 12, 'Adozione delle migliori pratiche per la gestione operativa della sicurezza IT.'),
  ('Sviluppo software', 'swdev', 13, 'Sicurezza nel ciclo di sviluppo del software e gestione delle vulnerabilità.')
ON CONFLICT DO NOTHING;

-- Seed assessment questions
INSERT INTO assessment_questions (category_id, order_index, question_text, description) VALUES
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 1, 'L''organizzazione ha definito e documentato gli obiettivi di continuità operativa che devono essere perseguiti nella gestione degli scenari di crisi?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 2, 'L''organizzazione ha effettuato una business impact analysis per identificare i servizi essenziali e individuare le risorse necessarie per garantirne l''erogazione?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 3, 'Esistono criteri per valutare la gravità dell''interruzione operativa causata da un incidente?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 4, 'La sicurezza delle informazioni e la continuità dei servizi essenziali sono stati descritti/documentati e inclusi nei piani di continuità (BCP)?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 5, 'L''organizzazione ha approvato politiche e procedure per la gestione del backup di dati e applicazioni su dispositivi, supporti di archiviazione, cloud, DB e server?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 6, 'L''organizzazione ha predisposto soluzioni di disaster recovery (DR)?', 'Priorità: BASSA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 7, 'L''Organizzazione ha prevista la ridondanza di tutti i sistemi per garantire la disponibilità dell''impianto di elaborazione delle informazioni ed erogazione dei servizi principali?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 8, 'La tua organizzazione gestisce e verifica le procedure di backup delle informazioni?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 9, 'Eseguite test sui vostri sistemi di backup per garantire che i dati possano essere ripristinati correttamente?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 10, 'Il personale coinvolto riceve formazione e partecipa a esercitazioni di simulazione di crisi?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'bcp'), 11, 'Esiste un processo per gestire i requisiti di capacity di tutti i sistemi in base al processo aziendale e alla sua criticità?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'cert'), 12, 'L''Organizzazione ha implementato un sistema per la gestione della qualità certificato ISO 9001?', 'Priorità: BASSA'),
  ((SELECT id FROM assessment_categories WHERE code = 'cert'), 13, 'L''Organizzazione ha implementato un sistema per la gestione della qualità certificato ISO/IEC 27001?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'cert'), 14, 'Esiste una procedura per monitorare la disponibilità di nuovi schemi di certificazione, linee guida e indicazioni per la sicurezza sicurezza?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'crypto'), 15, 'La tua organizzazione utilizza soluzioni di comunicazione vocale, video e di testo protette?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'crypto'), 16, 'Esistono politiche per l''utilizzo di strumenti di videoconferenza protetti per garantire la sicurezza delle riunioni aziendali?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'crypto'), 17, 'I dispositivi aziendali sono crittografati e protetti contro gli accessi non autorizzati?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'crypto'), 18, 'La crittografia è applicata a tutte le comunicazioni di rete per evitare intercettazioni?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'crypto'), 19, 'Le chiavi crittografiche sono protette contro l''accesso non autorizzato e lo smarrimento?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'crypto'), 20, 'Disponete di politiche e procedure formali e documentate che specificano l''uso della crittografia e della cifratura all''interno della vostra organizzazione?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 21, 'La tua organizzazione gestisce le autorizzazioni all''accesso a reti e sistemi (inclusi i privilegi minimi e la separazione dei compiti)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 22, 'Esiste una politica/procedura documentata che descrive il processo di gestione degli accessi logici e fisici a reti e sistemi?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 23, 'Applicate il principio del privilegio minimo, assicurandovi che gli utenti abbiano solo l''accesso necessario per svolgere le loro funzioni lavorative?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 24, 'Esistono procedure per concedere e revocare l''accesso in base a cambiamenti di ruolo, promozioni o interruzioni del rapporto di collaborazione?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 25, 'I profili autorizzativi e i diritti di accesso sono rivisti periodicamente?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 26, 'Gli utenti di reti e sistemi dispongono di identificativo (user ID) univoco?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 27, 'Avete adottato una politica per l''utilizzo di password di accesso sicure?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 28, 'Monitorate e registrate l''accesso logico ai sistemi e ai dati critici?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 29, 'I log di accesso vengono verificati periodicamente per individuare attività insolite o non autorizzate?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 30, 'Esistono strumenti per verificare e modificare regolarmente i diritti di accesso?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 31, 'La tua organizzazione gestisce l''accesso remoto?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 32, 'Utilizzate metodi di autenticazione avanzati (ad esempio autenticazione a più fattori, MFA) per accedere a sistemi critici e informazioni sensibili, ivi inclusi i dati particolari?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 33, 'La tua organizzazione gestisce e protegge l''accesso fisico alle risorse?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 34, 'Esistono politiche e procedure per gestire l''accesso fisico, inclusi meccanismi di controllo degli ingressi e strumenti come i badge?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 35, 'La tua organizzazione gestisce le identità e le credenziali per le entità autorizzate, le funzioni e le transazioni?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'iam'), 36, 'Ogni utente è dotato di un identificativo unico e personale (User ID) per garantire la tracciabilità delle azioni svolte?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 37, 'L''organizzazione ha istituito un team dedicato alla gestione degli incidenti di sicurezza informatica (IRT o CSIRT)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 38, 'Sono state definite e documentate le politiche e le procedure per la gestione degli incidenti di sicurezza, incluse le fasi di individuazione, analisi e classificazione, contenimento, eradicazione, ripristino e attività post-incidente?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 39, 'Esistono meccanismi per la notifica tempestiva di un incidente ai soggetti interni ed esterni pertinenti (ad esempio, autorità, clienti, partner)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 40, 'Sono stati stabiliti livelli di classificazione per valutare la gravità degli incidenti e determinare le azioni di risposta appropriate?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 41, 'Esiste un processo di lessons learned per analizzare gli incidenti passati e migliorare le misure di prevenzione e risposta?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 42, 'Il personale è formato sulle procedure di gestione degli incidenti e partecipa regolarmente a esercitazioni e simulazioni?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 43, 'L''organizzazione dispone di un piano di comunicazione interna ed esterna in caso di incidente significativo?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 44, 'Viene effettuato il monitoraggio continuo degli eventi di sicurezza e delle anomalie di rete?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 45, 'Sono implementate soluzioni tecnologiche per il rilevamento automatizzato degli incidenti (IDS, IPS, SIEM, EDR)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 46, 'L''organizzazione è in grado di isolare rapidamente i sistemi compromessi per contenere un incidente?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 47, 'È stato definito e pianificato un iter autorizzativo per determinare la notifica di un incidente significativo allo CSIRT Italia e/o all''Autorità competente NIS, in conformità con la Direttiva NIS2?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 48, 'Esistono procedure per la raccolta e la conservazione delle prove digitali in caso di indagini forensi?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 49, 'L''organizzazione partecipa a network di condivisione delle informazioni sulle minacce (ISAC, CERT nazionali o europei)?', 'Priorità: BASSA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 50, 'I rapporti sugli incidenti vengono condivisi internamente per aumentare la consapevolezza del personale?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 51, 'L''organizzazione implementa un processo di rilevamento e gestione delle violazioni dei dati personali (data breach) in conformità con il GDPR e la NIS2?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 52, 'Sono state implementate procedure per rispondere a diversi tipi di incidenti (ransomware, phishing, DDoS, insider threat, ecc.)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 53, 'Esistono accordi di supporto con fornitori esterni specializzati per la gestione di incidenti complessi?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 54, 'L''organizzazione dispone di strumenti e procedure per il ripristino rapido dei servizi essenziali dopo un incidente?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 55, 'Sono stati implementati canali sicuri di comunicazione per scambiare informazioni tra i responsabili della sicurezza riguardo la gestione dell''incidente?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 56, 'Il piano di gestione degli incidenti viene rivisto e aggiornato almeno annualmente o dopo ogni incidente significativo?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 57, 'Sono state stabilite metriche e indicatori chiave (KPI) per misurare l''efficacia del processo di gestione degli incidenti (tempo medio di rilevamento, tempo medio di risposta, ecc.)?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 58, 'Esiste un processo di escalation chiaro per gestire gli incidenti che richiedono il coinvolgimento di livelli decisionali superiori?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 59, 'L''organizzazione ha previsto la gestione degli incidenti di sicurezza anche dal punto di vista legale e contrattuale (ad esempio, notifiche ai clienti, obblighi verso i partner)?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'incident'), 60, 'L''organizzazione dispone di una copertura assicurativa contro i rischi derivanti da incidenti informatici (cyber insurance)?', 'Priorità: BASSA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 61, 'L''organizzazione ha definito e implementato un processo di analisi del rischio che considera le principali minacce cyber e le vulnerabilità dei propri sistemi?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 62, 'L''analisi del rischio copre anche i rischi legati ai fornitori e alla catena di approvvigionamento?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 63, 'Vengono valutati regolarmente (almeno annualmente) i rischi derivanti dall''uso di nuove tecnologie e dall''evoluzione delle minacce informatiche?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 64, 'Esiste un registro dei rischi (risk register) che documenta i rischi identificati, le relative valutazioni e le misure di mitigazione adottate?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 65, 'L''organizzazione ha definito criteri di accettazione del rischio (risk appetite) approvati dal management?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 66, 'Vengono condotte analisi di rischio specifiche prima dell''introduzione di nuovi sistemi, servizi o modifiche significative all''infrastruttura IT?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 67, 'Le misure di mitigazione dei rischi identificati sono monitorate e la loro efficacia viene rivalutata periodicamente?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'risk'), 68, 'L''analisi del rischio include la valutazione dell''impatto operativo, finanziario e reputazionale di un potenziale incidente di sicurezza?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 69, 'L''organizzazione mantiene un inventario completo e aggiornato di tutti gli asset IT (hardware, software, dati, infrastrutture di rete)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 70, 'Gli asset IT sono classificati in base alla loro criticità per il business e alla sensibilità dei dati che trattano?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 71, 'Esiste un processo per la gestione del ciclo di vita degli asset, inclusi l''acquisto, l''installazione, la manutenzione e la dismissione sicura?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 72, 'L''inventario degli asset è integrato con le valutazioni del rischio per identificare le aree di maggiore esposizione?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 73, 'Le politiche di gestione degli asset IT prevedono la rimozione sicura dei dati prima della dismissione o del riutilizzo dei dispositivi?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 74, 'Esiste un processo di monitoraggio per rilevare asset non autorizzati o non gestiti all''interno della rete aziendale?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 75, 'L''inventario degli asset viene aggiornato automaticamente o comunque con cadenza regolare?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 76, 'Le responsabilità per la gestione e la sicurezza di ciascun asset sono chiaramente assegnate a un proprietario (asset owner)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 77, 'L''organizzazione utilizza strumenti di discovery automatizzati per identificare nuovi dispositivi e servizi connessi alla rete?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 78, 'La classificazione degli asset tiene conto dei requisiti normativi applicabili (NIS2, GDPR, ecc.)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 79, 'Esiste un processo per gestire e tracciare le licenze software per prevenire l''uso di software non autorizzato o vulnerabile?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'asset'), 80, 'La tua organizzazione ha un inventario delle informazioni e dei sistemi?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 81, 'Esistono procedure per valutare e monitorare la sicurezza informatica dei fornitori e dei partner lungo la catena di approvvigionamento?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 82, 'I contratti con i fornitori includono requisiti specifici di sicurezza informatica e clausole relative alla gestione degli incidenti?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 83, 'L''organizzazione conduce audit periodici sui fornitori critici per verificare il rispetto dei requisiti di sicurezza concordati?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 84, 'Esiste un processo per valutare l''impatto sulla sicurezza dell''organizzazione derivante da una compromissione di un fornitore?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 85, 'I fornitori sono classificati in base al livello di rischio che rappresentano per l''organizzazione?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 86, 'Esiste un piano di risposta in caso di incidente che coinvolga un fornitore critico?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 87, 'L''organizzazione verifica che i fornitori di servizi cloud e tecnologici adottino misure di sicurezza adeguate (certificazioni, standard internazionali)?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 88, 'Vengono effettuate valutazioni dei rischi legati alla dipendenza da singoli fornitori (single point of failure)?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 89, 'La catena di approvvigionamento è monitorata per identificare potenziali vulnerabilità introdotte da aggiornamenti software, patch o componenti di terze parti?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 90, 'I fornitori sono tenuti a notificare tempestivamente all''organizzazione qualsiasi incidente di sicurezza che possa avere un impatto sui servizi forniti?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'supply'), 91, 'L''organizzazione ha definito una strategia di diversificazione dei fornitori per ridurre i rischi legati alla catena di approvvigionamento?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 92, 'L''impegno degli organi direttivi dell''organizzazione in materia di sicurezza informatica è dimostrato politiche e obiettivi definiti, compatibili con la direzione strategica dell''organizzazione?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 93, 'La tua organizzazione ha definito i ruoli e le responsabilità per la sicurezza informatica internamente per il personale dipendente ed esternamente per le terze parti (ad esempio, fornitori, clienti e appaltatori)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 94, 'Le politiche e le procedure adottate per garantire la sicurezza di reti e sistemi sono allineate ai principali standard di sicurezza informatica (ad esempio, ISO/IEC 27001, NIST)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 95, 'Le politiche e procedure pertinenti la sicurezza di reti e sistemi sono riviste e aggiornate periodicamente?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 96, 'Esiste una persona o un team designato responsabile della supervisione delle politiche e delle pratiche di sicurezza informatica?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 97, 'Gli organi direttivi sono consapevoli della loro potenziale responsabilità in caso di inosservanza degli adempimenti normativi previsti dalla NIS2?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 98, 'I membri degli organi direttivi sono tenuti a sottoporsi a una formazione periodica sulla sicurezza informatica?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 99, 'Esiste una documentazione attestante la partecipazione e il completamento dei programmi di formazione da parte di tutti i membri degli organi direttivi?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'gov'), 100, 'Tutti gli utenti privilegiati nella tua organizzazione comprendono i propri ruoli e responsabilità?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 101, 'La tua organizzazione fornisce formazione sulla sicurezza informatica al personale?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 102, 'I nuovi dipendenti ricevono una formazione specifica sulla sicurezza informatica durante il processo di onboarding?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 103, 'Il programma di formazione viene aggiornato periodicamente per riflettere le nuove minacce e le migliori pratiche di sicurezza?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 104, 'Esiste un piano di sensibilizzazione continua (awareness) per mantenere alta l''attenzione sulla sicurezza informatica?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 105, 'I dipendenti vengono sottoposti a test periodici (ad esempio, simulazioni di phishing) per verificare la loro capacità di riconoscere le minacce informatiche?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 106, 'Vengono fornite formazioni specialistiche al personale IT e ai responsabili della sicurezza informatica?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 107, 'Esiste una politica di sicurezza informatica specifica per il personale che lavora da remoto?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 108, 'Le competenze in materia di cybersecurity vengono valutate come parte del processo di selezione per i ruoli critici?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 109, 'Sono previste procedure disciplinari chiare per le violazioni delle politiche di sicurezza informatica?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hr'), 110, 'Sono state definite procedure per la gestione sicura delle cessazioni del rapporto di lavoro (revoca accessi, restituzione asset, ecc.)?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hygiene'), 111, 'L''organizzazione ha implementato una politica per la gestione degli aggiornamenti e delle patch di sicurezza su tutti i sistemi e dispositivi?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hygiene'), 112, 'Sono utilizzate soluzioni antivirus e antimalware aggiornate su tutti gli endpoint?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hygiene'), 113, 'Gli utenti sono obbligati a utilizzare password robuste e a cambiarle periodicamente?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hygiene'), 114, 'Esistono regole chiare sull''uso dei dispositivi personali (BYOD) e sulla connessione a reti aziendali?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'hygiene'), 115, 'L''organizzazione esegue scansioni periodiche delle vulnerabilità su reti, sistemi e applicazioni?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 116, 'L''organizzazione esegue audit di sicurezza interni o esterni almeno annualmente?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 117, 'Vengono condotti penetration test periodici per verificare la robustezza delle difese informatiche?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 118, 'I risultati degli audit e dei test vengono documentati e utilizzati per piani di miglioramento?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 119, 'L''organizzazione ha implementato un processo strutturato per il miglioramento continuo della postura di sicurezza (PDCA o equivalente)?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 120, 'I contratti di manutenzione dei sistemi critici includono SLA specifici per la sicurezza?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 121, 'L''organizzazione monitora le metriche di sicurezza (KPI/KRI) per valutare l''efficacia delle misure adottate?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 122, 'Esiste un processo per gestire i cambiamenti (change management) che include la valutazione dell''impatto sulla sicurezza?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 123, 'Le segnalazioni di sicurezza e le raccomandazioni degli organi di vigilanza vengono recepite e implementate tempestivamente?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 124, 'L''organizzazione partecipa a iniziative di benchmarking per confrontare la propria postura di sicurezza con quella di organizzazioni simili?', 'Priorità: BASSA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 125, 'Vengono effettuate revisioni post-incidente con l''obiettivo di migliorare i processi di prevenzione e risposta?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'maint'), 126, 'L''organizzazione ha definito un programma formale di manutenzione preventiva per tutti i sistemi IT critici?', 'Priorità: MEDIA'),
  ((SELECT id FROM assessment_categories WHERE code = 'netsec'), 127, 'La rete aziendale è segmentata per limitare la propagazione di eventuali attacchi?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'netsec'), 128, 'Sono implementati firewall e sistemi di filtraggio del traffico a livello perimetrale e interno?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'netsec'), 129, 'Viene effettuato il monitoraggio continuo del traffico di rete per rilevare anomalie e potenziali minacce?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'netsec'), 130, 'L''accesso alla rete wireless è protetto da meccanismi di autenticazione e crittografia adeguati?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'swdev'), 131, 'L''organizzazione adotta pratiche di sviluppo sicuro del software (Secure SDLC) che integrano la sicurezza in tutte le fasi del ciclo di sviluppo?', 'Priorità: ALTA'),
  ((SELECT id FROM assessment_categories WHERE code = 'swdev'), 132, 'Vengono condotti test di sicurezza del codice (code review, SAST, DAST) prima del rilascio in produzione?', 'Priorità: ALTA')
ON CONFLICT DO NOTHING;