// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcllvyzhefcqftesahnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjbGx2eXpoZWZjcWZ0ZXNhaG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzUyMTUsImV4cCI6MjA2NzExMTIxNX0.wzDcO5RkVKQXSMBftT8oGvv4SRG7wjeJr87DQwWh4zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});